// ======================================================
// Canvas Utilities
// ======================================================

export function resizeCanvas(canvas) {
  if (!canvas) return;

  const ratio = window.devicePixelRatio || 1;

  const rect = canvas.getBoundingClientRect();

  const width = Math.floor(rect.width * ratio);
  const height = Math.floor(rect.height * ratio);

  if (
    canvas.width !== width ||
    canvas.height !== height
  ) {
    canvas.width = width;
    canvas.height = height;

    const ctx = canvas.getContext("2d");

    ctx.setTransform(
      ratio,
      0,
      0,
      ratio,
      0,
      0
    );
  }
}

// ======================================================
// Rounded Rectangle
// ======================================================

export function roundRect(
  ctx,
  x,
  y,
  width,
  height,
  radius = 8
) {
  ctx.beginPath();

  ctx.moveTo(x + radius, y);

  ctx.lineTo(x + width - radius, y);

  ctx.quadraticCurveTo(
    x + width,
    y,
    x + width,
    y + radius
  );

  ctx.lineTo(
    x + width,
    y + height - radius
  );

  ctx.quadraticCurveTo(
    x + width,
    y + height,
    x + width - radius,
    y + height
  );

  ctx.lineTo(
    x + radius,
    y + height
  );

  ctx.quadraticCurveTo(
    x,
    y + height,
    x,
    y + height - radius
  );

  ctx.lineTo(
    x,
    y + radius
  );

  ctx.quadraticCurveTo(
    x,
    y,
    x + radius,
    y
  );

  ctx.closePath();
}

// ======================================================
// Clamp
// ======================================================

export function clamp(
  value,
  min,
  max
) {
  return Math.max(
    min,
    Math.min(max, value)
  );
}

// ======================================================
// Lerp
// ======================================================

export function lerp(
  start,
  end,
  amount
) {
  return start + (end - start) * amount;
}



//was generated by chatgpt twice
// ======================================================
// Canvas Utilities
// ======================================================
/*
export function resizeCanvas(canvas) {
  if (!canvas) return;

  const ratio = window.devicePixelRatio || 1;

  const rect = canvas.getBoundingClientRect();

  const width = Math.max(rect.width, 300);
  const height = Math.max(rect.height, 180);

  canvas.width = width * ratio;
  canvas.height = height * ratio;

  const ctx = canvas.getContext("2d");

  ctx.setTransform(ratio, 0, 0, ratio, 0, 0);

  return {
    width,
    height,
    ctx
  };
}

export function roundRect(ctx, x, y, w, h, r) {
  ctx.beginPath();

  ctx.moveTo(x + r, y);

  ctx.lineTo(x + w - r, y);

  ctx.quadraticCurveTo(x + w, y, x + w, y + r);

  ctx.lineTo(x + w, y + h - r);

  ctx.quadraticCurveTo(x + w, y + h, x + w - r, y + h);

  ctx.lineTo(x + r, y + h);

  ctx.quadraticCurveTo(x, y + h, x, y + h - r);

  ctx.lineTo(x, y + r);

  ctx.quadraticCurveTo(x, y, x + r, y);

  ctx.closePath();
}
  */